// 30-vue-default/src/components/Counter.vue
<template>
  <div class="counter">
    <div class="counter-display">{{ state.count }}</div>
    <div>
      <v-btn @click="decrease" color="primary" class="counter-btn">-</v-btn>
      <v-btn @click="increase" color="primary" class="counter-btn">+</v-btn>
    </div>
    <div>
      <v-btn @click="toggle" color="primary" class="counter-btn">Toggle</v-btn>
    </div>
  </div>
</template>

<script lang="ts">
import { defineComponent, reactive, computed, onMounted } from '@vue/composition-api';

const Component = defineComponent({
  setup() {
    const state = reactive({
      count: 0
    });

    // onMounted(() => {
    //   setInterval(() => {
    //     state.count++;
    //   }, 1000);
    // });

    function increase() {
      state.count++;
    }

    function decrease() {
      state.count--;
    }

    function toggle() {
      setInterval(() => {
        state.count++;
      }, 1000);
    }

    return {
      state,
      increase,
      decrease,
      toggle
    };
  }
});

export default Component;
</script>

<style scoped>
.counter {
  display: flex;
  flex-direction: column;
  align-items: center;
  background-color: lightcyan;
  padding: 30px;
}

.counter-display {
  margin: 5px;
  padding: 15px;
  border: purple solid 2px;
  width: 100px;
  display: flex;
  flex-direction: column;
  align-items: center;
  font-size: xx-large;
}

.counter-btn {
  margin: 4px;
}
</style>

// 20-react-default/src/Counter.tsx
import React, { useEffect, useRef, useState } from 'react';
import { createStyles, makeStyles } from '@material-ui/core/styles';
import Button from '@material-ui/core/Button';

const useStyles = makeStyles(createStyles({
    counter: {
        display: "flex",
        flexDirection: "column",
        alignItems: "center",
        backgroundColor: 'lightcyan',
        padding: 20,
    },
    counterDisplay: {
        width: 100,
        margin: 5,
        padding: 15,
        border: "purple solid 2px",
        fontSize: "xx-large",
    },
    button: {
        margin: 4
    }
}));

export function Counter() {

    const classes = useStyles();

    const [count, setCount] = useState(0);
    const intervalRef = useRef<number>();

    useEffect(() => {
        setInterval(() => {
            setCount(count => count + 1)
        }, 1000)
    }, []);

    function increase() {
        setCount(count + 1);
    }

    function decrease() {
        setCount(count - 1);
    }

    function toggle() {
        if (!intervalRef.current) {
            intervalRef.current = window.setInterval(() => {
                setCount(count => count + 1)
            }, 1000)
        } else {
            clearInterval(intervalRef.current);
            intervalRef.current = undefined;
        }
    }

    return (
        <div className={classes.counter}>

            <div className={classes.counterDisplay}> {count} </div>
            <div>
                <div>
                    <Button onClick={decrease} variant="contained" color="primary" className={classes.button}>-</Button>
                    <Button onClick={increase} variant="contained" color="primary" className={classes.button}>+</Button>
                </div>

                <div>
                    <Button onClick={toggle} variant="contained" color="primary"
                            className={classes.button}>Toggle</Button>
                </div>
            </div>
        </div>
    );
}
