// 20-react-default/src/Counter.tsx
import React, { useEffect, useRef, useState } from 'react';

export function Counter() {

    const [count, setCount] = useState(0);
    let intervalRef = useRef<number>();

    useEffect(() => {
        setInterval(() => {
            setCount(count => count + 1)
        }, 1000)
    }, []);

    function increase(){
        setCount(count + 1);
    }

    function decrease(){
        setCount(count - 1);
    }

    function toggle() {
        if (!intervalRef.current) {
            intervalRef.current = window.setInterval(() => {
                setCount(count => count + 1)
            }, 1000)
        } else {
            clearInterval(intervalRef.current);
            intervalRef.current = undefined;
        }
    }

    return (
        <>
            <div> {count} </div>
            <div>
                <button onClick={decrease}>-</button>
                <button onClick={increase}>+</button>
            </div>
            <div>
                <button onClick={toggle}>Toggle</button>
            </div>
        </>
    );
}

// 10-angular-default/src/app/counter/counter.component.ts
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-counter',
  template: `
    <div>
      {{count}}
    </div>
    <div>
      <button (click)="increase()">+</button>
      <button (click)="decrease()">-</button>
    </div>
    <div>
      <button (click)="toggle()">Toggle</button>
    </div>
  `,
  styleUrls: ['./counter.component.css']
})
export class CounterComponent implements OnInit {

  count = 0;
  private intervalHandle;

  constructor() {}

  ngOnInit(): void {
  }

  increase() {
    this.count++;
  }

  decrease() {
    this.count--;
  }

  toggle() {
    if (!this.intervalHandle) {
      this.intervalHandle = setInterval(() => {
        this.count++;
      }, 1000);
    } else {
      clearInterval(this.intervalHandle);
      this.intervalHandle = undefined;
    }
  }
}
